site_name: AdvancedText
repo_url: https://rakugoteam.github.io/advanced-text-docs/

extra:
  homepage: https://rakugoteam.github.io
  version:
    provider: mike
  alternate:
    - name: English
      link: /
      lang: en

theme:
  name: material
  logo: logo.png
  palette:
    scheme: slate
    primary: deep purple
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
